name: Setup Octopilot
description: Download and install Octopilot (https://github.com/dailymotion-oss/octopilot)
inputs:
  version:
    required: false
    description: "Octopilot version to install, e.g. '1.2.23' (https://github.com/dailymotion-oss/octopilot/releases)"
runs:
  using: composite
  steps:
    - name: Determine version
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        if [ -z "${VERSION}" ]; then
          echo "Looking for latest version of Octopilot at https://github.com/dailymotion-oss/octopilot/releases/latest"
          VERSION=$(curl -sI https://github.com/dailymotion-oss/octopilot/releases/latest | grep "location: " | sed 's:.*/::' | tr -d '\r')
        fi
        # Remove any 'v' prefix:
        VERSION="${VERSION/#v}"
        echo "Found Octopilot version '${VERSION}'."
        echo "VERSION=${VERSION}" >> "${GITHUB_ENV}"
    - name: Download
      shell: bash
      run: |
        echo "Downloading Octopilot version '${VERSION}' from https://github.com/dailymotion-oss/octopilot/releases/tag/v${VERSION}"
        curl -fLO https://github.com/dailymotion-oss/octopilot/releases/download/v${VERSION}/octopilot_${VERSION}_checksums.txt
        curl -fLO https://github.com/dailymotion-oss/octopilot/releases/download/v${VERSION}/octopilot_${VERSION}_linux_amd64
        check=$(sha256sum -c octopilot_${VERSION}_checksums.txt 2>&1 || true)
        grep "OK" <<< "$check"
    - name: Add to $PATH
      shell: bash
      run: |
        mkdir -p .octopilot/bin
        mv octopilot_${VERSION}_linux_amd64 .octopilot/bin/octopilot
        chmod +x .octopilot/bin/octopilot
        realpath .octopilot/bin >> "$GITHUB_PATH"
 
