name: Test octopilot action

on:
  pull_request:

jobs:
  latest:
    name: GitHub Action latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: MPV/octopilot@patch-1 # ./action.yml
    - run: octopilot --help

  specific:
    name: GitHub Action
    strategy:
      fail-fast: false
      matrix:
        version:
          - v1.2.23
          - 1.2.23
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: MPV/octopilot@patch-1 # ./action.yml
      with:
        version: ${{ matrix.version }}
    - run: octopilot --help
